# Generated by Django 4.0.2 on 2022-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Speciality', 'verbose_name_plural': 'Specialities'},
        ),
    ]
